name: GHCR Delete Image

description: > 
  Delete GitHub Container Registry Image by specified tag (or without tag).
  Mutually exclusive options: tag, untagged-all
  

author: bots-house

branding:
  icon: delete
  color: blue

inputs:
  is-user:
    description: >
      Owner of the is user (not organization)
    required: false

  owner:  
    description: >
      Owner of the package (user or organization)
    required: true
    
  name: 
    description: >
      Name of the package containing the version to delete.
    required: true
    
  token: 
    description: > 
      Token with the necessary scopes to delete package versions.
    required: true
  
  tag:
    description: > 
      Tag to delete
    required: false

  untagged-all:
    description:  >
      Delete all untagged images

runs:
  using: 'node16'
  main: 'dist/index.js'
